packages:
  - front-app
  - libs/*
  - backend-app
autoInstallPeers: false
onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - edgedriver
  - esbuild
  - geckodriver
patchedDependencies:
  "@embroider/vite": patches/@embroider__vite.patch
catalog:
  "@babel/core": ~7.28.6
  "@babel/plugin-transform-runtime": ~7.28.5
  "@ember-data/debug": 5.8.1
  "@ember-intl/vite": ~0.5.0
  "@ember/library-tsconfig": ~2.0.0
  "@ember/optional-features": ^2.3.0
  "@ember/string": ^4.0.1
  "@ember/test-waiters": ^4.1.1
  "@embroider/addon-dev": ~8.2.0
  "@embroider/addon-shim": ~1.10.2
  "@embroider/compat": ~4.1.12
  "@embroider/config-meta-loader": ^1.0.0
  "@embroider/core": ~4.4.2
  "@embroider/legacy-inspector-support": ^0.1.3
  "@embroider/macros": ~1.19.6
  "@embroider/router": ~3.0.6
  "@embroider/vite": ~1.5.0
  "@eonasdan/tempus-dominus": ~6.10.4
  "@fastify/cookie": ^11.0.2
  "@fastify/cors": ^11.0.0
  "@fastify/flash": ^6.0.3
  "@fastify/passport": ^3.0.2
  "@fastify/secure-session": ^8.1.1
  "@fastify/session": ^11.1.0
  "@fastify/static": ^9.0.0
  "@fastify/swagger": ^9.4.2
  "@fastify/swagger-ui": ^5.2.1
  "@glimmer/component": ^2.0.0
  "@glint/environment-ember-loose": ^1.5.2
  "@glint/template": ~1.7.3
  "@glint/tsserver-plugin": ^2.0.0
  "@mikro-orm/cli": ~6.6.6
  "@mikro-orm/core": ~6.6.6
  "@mikro-orm/seeder": ~6.6.6
  "@mikro-orm/sqlite": ~6.6.6
  "@ngneat/falso": ^8.0.2
  "@playwright/test": ^1.58.0
  "@rollup/plugin-alias": ^6.0.0
  "@swc/core": ^1.10.8
  "@tailwindcss/vite": ^4.1.18
  "@testcontainers/rabbitmq": ^11.11.0
  "@types/amqplib": ^0.10.6
  "@types/handlebars": ^4.1.0
  "@types/jsonwebtoken": ^9.0.8
  "@types/nodemailer": ^7.0.9
  "@types/passport-http-bearer": ^1.0.41
  "@types/passport-jwt": ^4.0.1
  "@types/passport-local": ^1.0.38
  "@types/pdf-parse": ^1.1.5
  "@types/rsvp": ^4.0.9
  "@typescript/native-preview": ~7.0.0-dev.20260202.1
  "@vitest/browser-playwright": ^4.0.18
  "@vitest/coverage-v8": 4.0.18
  "@vitest/ui": 4.0.18
  "@warp-drive/build-config": 5.8.1
  "@warp-drive/core": 5.8.1
  "@warp-drive/core-types": 5.8.1
  "@warp-drive/ember": 5.8.1
  "@warp-drive/experiments": ~0.2.7
  "@warp-drive/json-api": 5.8.1
  "@warp-drive/legacy": 5.8.1
  "@warp-drive/utilities": 5.8.1
  amqplib: ^0.10.5
  argon2: ^0.44.0
  daisyui: ~5.5.14
  date-fns: ~4.1.0
  decorator-transforms: ~2.3.1
  ember-basic-dropdown: ^8.11.0
  ember-cli: ~6.10.0
  ember-cli-babel: ^8.2.0
  ember-cli-deprecation-workflow: ^4.0.0
  ember-cli-flash: ^6.0.0
  ember-cli-page-object: ^2.3.2
  ember-concurrency: ^5.1.0
  ember-flatpickr: ^9.0.2
  ember-immer-changeset: ~2.0.0
  ember-intl: ~8.0.3
  ember-load-initializers: ^3.0.1
  ember-modifier: ^4.2.2
  ember-page-title: ^9.0.3
  ember-resolver: ~13.1.1
  ember-resources: ^7.0.7
  ember-simple-auth: ^8.2.0
  ember-simple-auth-token: ~6.0.1
  ember-source: ~6.10.0
  ember-strict-application-resolver: ^0.1.1
  ember-truth-helpers: ^5.0.0
  ember-vitest: ^0.3.3
  eslint-plugin-import: ^2.31.0
  fastify: ^5.2.1
  fastify-type-provider-zod: ^6.1.0
  fastify-zod: ^1.4.0
  flatpickr: ^4.6.13
  globals: ^17.1.0
  handlebars: ^4.7.8
  jsonwebtoken: ^9.0.2
  mailgen: ^2.0.29
  msw: ^2.12.7
  nodemailer: ^7.0.13
  openapi-msw: ^2.0.0
  oxfmt: ^0.28.0
  oxlint: ~1.43.0
  oxlint-tsgolint: ^0.11.4
  passport-http-bearer: ^1.0.1
  passport-jwt: ^4.0.1
  passport-local: ^1.0.0
  pdf-parse: ^2.4.5
  pino: ^10.3.0
  pino-pretty: ^13.0.0
  rollup: ~4.57.0
  rollup-plugin-copy: ^3.5.0
  stylelint: ^17.0.0
  stylelint-config-standard: ^40.0.0
  tailwindcss: ^4.1.18
  tracked-built-ins: ^4.0.0
  true-myth: ~9.3.1
  ts-dotenv: ^0.9.1
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  tsx: ^4.19.2
  turbo: ^2.7.4
  type-fest: ^5.4.3
  vite-plugin-node: ^7.0.0
  vite-tsconfig-paths: ^6.0.5
  webpack: ^5.104.1
