packages:
  - front-app
  - libs/*
autoInstallPeers: false
onlyBuiltDependencies:
  - edgedriver
  - geckodriver
patchedDependencies:
  '@embroider/vite': patches/@embroider__vite.patch
resolvePeersFromWorkspaceRoot: false
